### ISSUE TITLE
Unable to install psupplementary due to error

### ISSUE THREAD

**Issue by sushantbangru** [wmacnair/psupplementary#1]
This is the error I get when I tried installing. Was successfully able to install psupertime but without this unable to figure how to use your software to do analysis. Thanks.

─  preparing ‘psupplementary’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘psupplementary’ ...
   ** using staged installation
   ** R
   ** data
   *** moving datasets to lazyload DB
   Warning: file ‘acinar_sce.rda’ has magic number 'versi'
     Use of save versions prior to 2 is deprecated
   Error in load(zfile, envir = tmp_env) : 
     bad restore file magic number (file may be corrupted) -- no data loaded
   ERROR: lazydata failed for package ‘psupplementary’
─  removing ‘/tmp/RtmpMQ1qBj/Rinst1f1e2bc1da9c/psupplementary’
         -----------------------------------
   ERROR: package installation failed
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error

**Comment by wmacnair** [comment]
Hi @sushantbangru, thanks for bringing this up.

I would recommend trying installing with `devtools::install('path/to/packages/psupplementary')` rather than with the vignettes. Could you check whether that works?

I've just checked and at present installing with the vignettes doesn't work, as the calls to Seurat have changed with the latest Seurat versions. I'll look into updating that. But I think if you can get that to work, then you can read through the vignettes and try things out by hand, without actually needing to build them.

Cheers
Will
(Also apologies that it took so long to get to this. I only saw the issue recently, as it turns out github doesn't automatically watch repos that you create, which I find a bit strange. Future issues should be fine!)

**Comment by wmacnair** [comment]
Hi @sushantbangru 

I'm going to close this - very happy to reopen if you get back to this and it still doesn't work. 

Cheers
Will
